### ISSUE TITLE
UncaughtPromiseException when rejecting synchronous promise

### ISSUE THREAD

**Issue by kawapure** [YukisCoffee/CoffeeRequest#1]
Synchronous promises are a supported feature of CoffeeRequest's promise system. They are promises which wrap synchronous (non-generator) callbacks. These are considered synchronous promises as they will always finish execution in one call, without ever pausing execution to be resumed later.

Synchronous promises are explicitly handled by the execution engine. When a promise is created with a non-generator callback, the callback will be called instantly. Since this callback occurs before the promise finishes construction, and thus callbacks to register the rejection handlers haven't even had a chance to run yet, any call to the reject function will immediately trigger the logic to throw an exception because there isn't a catch registered.

It's possible to work around this currently by coercing your instantly-called callbacks into generators via including the yield keyword somewhere in the body (i.e. `if (false) yield;`):

```php
// Will crash:
$promise = new Promise(function($resolve, $reject) {
    $reject(new Exception("Test"));
});
$promise->catch(fn(Exception $e) => Logger::log($e));

// Will work perfectly fine:
$promise = new Promise(function($resolve, $reject) {
    if (false) yield; // Coerce the function into a generator
    $reject(new Exception("Test"));
});
$promise->catch(fn(Exception $e) => Logger::log($e));

```

A suggestion: for synchronous promises, there will only ever be one valid then and one valid catch handler. You can simply ignore the lack of a catch handler until the promise is destructed, which should preserve the error while enabling ergonomic use.

**Comment by YukisCoffee** [comment]
Fixed in e854b90.
